name: Auto Merge PR

on: 
  pull_request:
    types: [opened, reopened]

jobs:
  lint:
    runs-on: ubuntu-latest
  
    steps:

      - name: checkout
        uses: actions/checkout@v3

      - name: flake8 and pylint
        run: |
          pip install -r requirements.txt
          flake8 --ignore=E501,E231 *.py 
          pylint --errors-only --disable=C0301 --disable=C0326 *.py 

      # - name: unit test
      #   run: python -m unitttest --verbose --failfast

  merge:
    if: github.actor == 'ravinduf' || github.actor == 'octocat'
    needs: [lint]
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v3

      - name: Auto approve/merge Dependabot (native) PR
        # You may pin to the exact commit or the version.
        # uses: Yproximite/auto-approve-and-merge-dependabot-action@ce3d919aa61034cd0505f567044c466bba52b0a2
        uses: Yproximite/auto-approve-and-merge-dependabot-action@v0.1.0
        with:
          github-token:  ${{ secrets.GITHUB_TOKEN }}
    
          

