name: Auto Merge PR

on: 
  pull_request:
    types: [opened, reopened]
    

jobs:
  lint:
    runs-on: ubuntu-latest
  
    steps:

      - name: checkout
        uses: actions/checkout@v3

      - name: flake8 and pylint
        run: |
          pip install -r requirements.txt
          flake8 --ignore=E501,E231 *.py 
          pylint --errors-only --disable=C0301 --disable=C0326 *.py 

      # - name: unit test
      #   run: python -m unitttest --verbose --failfast

  merge:
    if: ${{ github.actor == 'ravinduf' }}
    needs: [lint]
    runs-on: ubuntu-latest
      
    steps:

      - uses: actions/checkout@v3
        
      - name: PR Automation
        uses: devjoes/pr-automation@v0.1.0
        with:
          autoMergeLabel: *
          

          

